export const X_GENERATOR_RESPONSE_NULLABLE = 'x-generator-response-nullable'
export const X_GENERATOR_TYPE = 'x-generator-type'
export const X_GENERATOR_NAMESPACE = 'x-generator-namespace'
export const X_NAMESPACE = 'x-namespace'
export const X_ENUM_NAMES = 'x-enum-names'
